### ISSUE TITLE
Module build Failed.

### ISSUE THREAD

**Issue by akashbiz** [strictd/angular2-ionic2-webpack#5]
Hello, I am facing this issue while setting up project using this repository.
Steps I have performed so far:

**clone the repo**
git clone --depth 1 https://github.com/strictd/angular2-ionic2-webpack.git

**change directory**
cd angular2-ionic2-webpack

**install the required packages with npm**
npm install

**install packages manually which are not loaded by above npm install command**

npm install gulp
npm install gulp-watch
npm install gulp-rename
npm install del
npm install run-sequence
npm install event-stream
npm install ionic-gulp-tslint
npm install tslint
npm install typescript
npm install webpack
npm install webpack-dev-server
npm install autoprefixer
npm install html-webpack-plugin
npm install extract-text-webpack-plugin
npm install copy-webpack-plugin
npm install tslint-loader
npm install core-js
npm install zone.js
npm install ts-helpers
npm install angular/core
npm install angular/platform-browser-dynamic
npm install angular/platform-browser
npm install angular/common
npm install angular/http
npm install angular/router
npm install rxjs
npm install angularclass/hmr
npm install awesome-typescript-loader
npm install angular2-template-loader
npm install angularclass/hmr-loader

**Issue facing:**

> Uncaught Error: Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at eval (eval at 36 (http://localhost:8080/js/vendor.js:6:1), <anonymous>:1:7)
    at Object.36 (http://localhost:8080/js/vendor.js:6:1)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at Object.81 (http://localhost:8080/js/vendor.js:14:18)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at webpackJsonpCallback (http://localhost:8080/js/polyfills.js:26:23)
    at http://localhost:8080/js/vendor.js:1:1
(anonymous) @ VM4383:1
36 @ vendor.js:6
__webpack_require__ @ polyfills.js:55
81 @ vendor.js:14
__webpack_require__ @ polyfills.js:55
webpackJsonpCallback @ polyfills.js:26
(anonymous) @ vendor.js:1

> Uncaught Error: Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
    at eval (eval at 34 (http://localhost:8080/js/app.js:6:1), <anonymous>:1:7)
    at Object.34 (http://localhost:8080/js/app.js:6:1)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at Object.79 (http://localhost:8080/js/app.js:14:18)
    at __webpack_require__ (http://localhost:8080/js/polyfills.js:55:30)
    at webpackJsonpCallback (http://localhost:8080/js/polyfills.js:26:23)
    at http://localhost:8080/js/app.js:1:1
(anonymous) @ VM4385:1
34 @ app.js:6
__webpack_require__ @ polyfills.js:55
79 @ app.js:14
__webpack_require__ @ polyfills.js:55
webpackJsonpCallback @ polyfills.js:26
(anonymous) @ app.js:1
client?8505:38 [WDS] Errors while compiling.
client?8505:80 ./src/browser/app/polyfills.ts

> Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/browser/app/polyfills.ts
errors @ client?8505:80
sock.onmessage @ socket.js?e5d0:37
EventTarget.dispatchEvent @ eventtarget.js?3e89:51
(anonymous) @ main.js?45b8:274
SockJS._transportMessage @ main.js?45b8:272
EventEmitter.emit @ emitter.js?927b:50
WebSocketTransport.ws.onmessage @ websocket.js?c17e:35
client?8505:80 ./src/browser/app/vendor.ts

> Module build failed: Error
    at new FatalError (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\error.js:40:23)
    at Function.findConfiguration (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint\lib\configuration.js:47:15)
    at parseConfigFile (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:44:24)
    at resolveOptions (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:35:27)
    at Object.module.exports (D:\temp\project setup\angular2-ionic2-webpack-master\node_modules\tslint-loader\index.js:139:17)
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/browser/app/vendor.ts
errors @ client?8505:80
sock.onmessage @ socket.js?e5d0:37
EventTarget.dispatchEvent @ eventtarget.js?3e89:51
(anonymous) @ main.js?45b8:274
SockJS._transportMessage @ main.js?45b8:272
EventEmitter.emit @ emitter.js?927b:50
WebSocketTransport.ws.onmessage @ websocket.js?c17e:35
client?8505:80 ./src/browser/app/main.ts

**Comment by AndreiDev** [comment]
@akashbiz any luck with this issue?

**Comment by akashbiz** [comment]
@AndreiDev no luck, I dropped this implementation as no response and no solution worked so far. In stead I have created a structure given below:
Common > Services
Mobile > Ionic 2 structure
Web > Angular2 with webpack structure
and building application from respective structure.

Hope this help you.

**Comment by strictd** [comment]
For whatever reason I wasn't following this repo anymore. Also this repo has been replaced with https://github.com/strictd/ngx-mono and https://github.com/strictd/ngx-mono-core

**Comment by akashbiz** [comment]
But there isn't any repo which has this folder structure. If you know any please suggest @strictd

**Comment by strictd** [comment]
I poked at updating this repo and it's not very happy. The newer repos i've put out are basically the same angular2 folder structure as this one. the biggest difference with the newer versions is that I moved the backend/ folder to src/api/ .. it allows me to typescript full circle from backend api to the end user client.

The newer repo https://github.com/strictd/ngx-mono-core allows you to build multiple angular2 projects under the same folder structure. allowing a developer to build out individual projects, or to lace the projects together with lazy loading to create one monolithic project.
